foreground #ffffff
background #0e1415

selection_foreground #000000
selection_background #aefeff
cursor #aefeff

color0  #1a1a1a
color8  #6e6e6e

color1  #c97b8f
color9  #c97b8f

color2  #8fae8a
color10 #8fae8a

color3  #c9bb8a
color11 #c9bb8a

color4  #7d93b3
color12 #7d93b3

color5  #a998b3
color13 #a998b3

color6  #7fa89e
color14 #7fa89e

color7  #b8b8b8
color15 #e8e8e8
